FROM ubuntu:20.04
MAINTAINER dkacetl
EXPOSE 50002

ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    apt-get update -y \
    && apt-get install -y curl gnupg gosu git wget \
       zip build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 \
       libevent-dev libboost-dev libboost-system-dev libboost-filesystem-dev libboost-test-dev \
       libsqlite3-dev libminiupnpc-dev libnatpmp-dev libzmq3-dev systemtap-sdt-dev libminiupnpc-dev libnatpmp-dev \
       systemtap-sdt-dev g++-arm-linux-gnueabihf \
       python3 python3-pip \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN git clone https://github.com/spesmilo/electrum-server.git
RUN cd electrum-server \
    && git checkout $(git describe --tags)

#RUN cd electrum-server && ./configure
