version: "3"
services:
  bitcoind:
    container_name: bitcoind
    image: btcplus/bitcoind:22
    command:
      - "-txindex=1"
      - "-server=1"
      - "-rpcbind=10.5.0.2"
      - "-rpcallowip=10.5.0.0/16"
      - "-rpcport=8332"
      - "-rpcuser=bitcoin"
      - "-rpcpassword=Test0101"
      - "-maxconnections=64"
      - "-zmqpubrawblock=tcp://10.5.0.2:18332"
      - "-zmqpubrawtx=tcp://10.5.0.2:18333"
      - "-zmqpubhashblock=tcp://10.5.0.2:18443"
      - "-zmqpubhashtx=tcp://10.5.0.2:183444"
    environment:
      BITCOIN_DATA: /home/bitcoin/.bitcoin
    expose:
      - "8332"
      - "8333"
      - "18332"
      - "18333"
      - "18443"
      - "18444"
    networks:
      btcplus-network:
        ipv4_address: 10.5.0.2
    volumes:
      - "bitcoin_datadir:/home/bitcoin/.bitcoin"

  lnd:
    container_name: lnd
    image: btcplus/lnd:v0.14.1-beta
    command:
      - "--bitcoin.active"
      - "--bitcoin.mainnet"
      - "--bitcoin.node=bitcoind"
      - "--bitcoind.rpchost=10.5.0.2"
      - "--bitcoind.rpcuser=bitcoin"
      - "--bitcoind.rpcpass=Test0101"
      - "--bitcoind.zmqpubrawblock=tcp://10.5.0.2:18332"
      - "--bitcoind.zmqpubrawtx=tcp://10.5.0.2:18333"
    expose:
      - "9735"
      - "10009"
    networks:
      btcplus-network:
        ipv4_address: 10.5.0.6
    volumes:
      - "lnd_datadir:/root/.lnd"

  electrumx:
    image: btcplus/electrumx:latest
    restart: on-failure
    ports:
      - 50001:50001 # electrum tcp
      - 50002:50002 # electrum ssl
      - 8000:8000 # local rpc
    networks:
      btcplus-network:
        ipv4_address: 10.5.0.3
    environment:
      DAEMON_URL: "http://bitcoin:Test0101@10.5.0.2:8332"
      COIN: "Bitcoin"
      CACHE_MB: 600 # issue on small computers like odroid
    volumes:
      - "electrumx_datadir:/data"

  maria_db:
    image: mariadb:10.3.32
    restart: on-failure
    stop_grace_period: 1m
    expose:
      - "3306"
    networks:
      btcplus-network:
        ipv4_address: 10.5.0.4
    volumes:
      - "maria_db_datadir:/var/lib/mysql"
      - "./scripts/maria_db:/docker-entrypoint-initdb.d"
    environment:
      MARIADB_USER: mempool
      MARIADB_PASSWORD: mempool
      MARIADB_ROOT_PASSWORD: mempool

  mempool_backend:
    image: btcplus/mempool-backend:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh 10.5.0.4:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - "mempool_backend_datadir:/backend/cache"
    networks:
      btcplus-network:
        ipv4_address: 10.5.0.5
    environment:
      RPC_HOST: "10.5.0.2"
      RPC_PORT: "8332"
      RPC_USER: "bitcoin"
      RPC_PASS: "Test0101"
      ELECTRUM_HOST: "10.5.0.3"
      ELECTRUM_PORT: "50001"
      ELECTRUM_TLS: "false"
      MYSQL_HOST: "10.5.0.4"
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASS: "mempool"
      BACKEND_MAINNET_HTTP_PORT: "8333"
      CACHE_DIR: "/backend/cache"
      MEMPOOL_CLEAR_PROTECTION_MINUTES: "20"

networks:
  btcplus-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

#  bitcoin-cli-info:
#    container_name: bitcoin-cli-info
#    image: btcplus/bitcoind:latest
#    command:
#      - "bitcoin-cli"
#      - "-rpcconnect="
#      - "-rpcallowip=0.0.0.0/0"
#      - "-rpcport=8332"
#      - "-rpcuser=bitcoin"
#      - "-rpcpassword=Test0101"
#      - "-maxconnections=64"
#      - "-zmqpubrawblock=tcp://0.0.0.0:18332"
#      - "-zmqpubrawtx=tcp://0.0.0.0:18333"
#      - "-zmqpubhashblock=tcp://0.0.0.0:18443"
#      - "-zmqpubhashtx=tcp://0.0.0.0:183444"
#    environment:
#      BITCOIN_DATA: /home/bitcoin/.bitcoin
#    expose:
#      - "8332"
#      - "8333"
#      - "18332"
#      - "18333"
#      - "18443"
#      - "18444"
#    volumes:
#      - "bitcoin_datadir:/home/bitcoin/.bitcoin"

#  btcpayserver:
#    restart: unless-stopped
#    image: nicolasdorier/btcpayserver:1.0.2.106
#    expose:
#    - "49392"
#    environment:
#      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Database=btcpayserver${NBITCOIN_NETWORK:-regtest}
#      BTCPAY_NETWORK: ${NBITCOIN_NETWORK:-regtest}
#      BTCPAY_BIND: 0.0.0.0:49392
#      BTCPAY_EXTERNALURL: ${BTCPAY_PROTOCOL:-https}://${BTCPAY_HOST}/
#      BTCPAY_ROOTPATH: ${BTCPAY_ROOTPATH:-/}
#      BTCPAY_SSHTRUSTEDFINGERPRINTS: ${BTCPAY_SSHTRUSTEDFINGERPRINTS}
#      BTCPAY_SSHKEYFILE: ${BTCPAY_SSHKEYFILE}
#      VIRTUAL_NETWORK: nginx-proxy
#      VIRTUAL_PORT: 49392
#      VIRTUAL_HOST: ${BTCPAY_HOST}
#      VIRTUAL_HOST_NAME: "btcpay"
#      SSL_POLICY: Mozilla-Modern
#      LETSENCRYPT_HOST: ${BTCPAY_HOST}
#      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-<no value>}
#      BTCPAY_CHAINS: "ltc,btc"
#      BTCPAY_BTCEXPLORERURL: http://nbxplorer:32838/
#      BTCPAY_BTCLIGHTNING: "type=clightning;server=unix://etc/clightning_bitcoin/lightning-rpc"
#    links:
#    - nbxplorer
#    - postgres
#    - clightning_litecoin
#    - clightning_bitcoin
#    volumes:
#    - "btcpay_datadir:/datadir"
#    - "nbxplorer_datadir:/root/.nbxplorer"
#    - "clightning_bitcoin_datadir:/etc/clightning_bitcoin"

#  nbxplorer:
##    restart: unless-stopped
#    image: nicolasdorier/nbxplorer:1.0.2.31
#    expose:
#    - "32838"
#    environment:
#      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
#      NBXPLORER_BIND: 0.0.0.0:32838
#      NBXPLORER_CHAINS: "ltc,btc"
#      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
#      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
#    volumes:
#    - "nbxplorer_datadir:/datadir"
#    - "bitcoin_datadir:/root/.bitcoin"
#    links:
#    - bitcoind

#  postgres:
##    restart: unless-stopped
#    image: postgres:9.6.5
#    volumes:
#    - "postgres_datadir:/var/lib/postgresql/data"

#  bitcoind_experiments:
#    build:
#      context: build-bitcoin-core-experiments
#      args:
#        TAG: "v22.0"
#    container_name: bitcoind
#    image: btcplus/bitcoind:v22.0
#    environment:
#      BITCOIN_CONF: |
#        txindex=1\n
#        datadir=/root/.bitcoin\n
#        server=1\n
#        blocksonly=0\n
#        rpcbind=127.0.0.1\n
#        rpcallowip=0.0.0.0/0\n
#        rpcport=8332\n
#        rpcuser=bitcoin\n
#        rpcpassword=Test0101\n
#        maxconnections=64\n
#        zmqpubrawblock=tcp://0.0.0.0:18332\n
#        zmqpubrawtx=tcp://0.0.0.0:18333\n
#        zmqpubhashblock=tcp://0.0.0.0:18443\n
#        zmqpubhashtx=tcp://0.0.0.0:183444\n
#    expose:
#    - "8332"
#    - "8333"
#    - "18332"
#    - "18333"
#    - "18443"
#    - "18444"
#    volumes:
#    - "bitcoin_datadir:/root/.bitcoin"

#  clightning_bitcoin:
#    image: nicolasdorier/clightning:v0.6.1
#    container_name: btcpayserver_clightning_bitcoin
#    restart: unless-stopped
#    environment:
#      LIGHTNINGD_NETWORK: ${NBITCOIN_NETWORK:-regtest}
#      LIGHTNINGD_CHAIN: btc
#      LIGHTNINGD_EXPLORERURL: "http://nbxplorer:32838/"
#      LIGHTNINGD_OPT: |
#        bitcoin-datadir=/etc/bitcoin
#        bitcoin-rpcconnect=bitcoind
#        announce-addr=${BTCPAY_HOST}:9735
#        bind-addr=0.0.0.0:9735
#        network=${NBITCOIN_NETWORK:-regtest}
#        alias=${LIGHTNING_ALIAS}
#        chain=btc
#    volumes:
#    - "clightning_bitcoin_datadir:/root/.lightning"
#    - "bitcoin_datadir:/etc/bitcoin"
#    - "nbxplorer_datadir:/root/.nbxplorer"
#    ports:
#    - "9735:9735"
#    links:
#    - nbxplorer
#    - bitcoind

volumes:
  electrumx_datadir:
  postgres_datadir: 
  maria_db_datadir: 
  btcpay_datadir: 
  nbxplorer_datadir: 
  bitcoin_datadir:
  lnd_datadir:
  mempool_backend_datadir:
  clightning_bitcoin_datadir: 
